/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package studentID;

import java.util.ArrayList;

public class App {
    ArrayList<Student> students = new ArrayList<Student>();

    public static void main(String[] args) {
        new App();
    }

    public App() {
        // add some students
        students.add(Student.buildStudent(16, "Evan"));
        students.add(Student.buildStudent(20, "jake"));
        students.add(Student.buildStudent(12, "Steve"));
        students.add(Student.buildStudent(17, "John"));

        // Dump student info
        for (Student x : students) {
            if (x != null) {
                System.out.println(x);
            }
        }
    }
}
