/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ca.retrylife.ics4u;

public class App {

    public static void main(String[] args) {
        System.out.println("Run each assignment from it's own App file");

    }
}
